/**
 * Bundled risk defaults — mirrored from Command Center Kalshi / Predict tab.
 * Also seeded into phone storage (`foresight.risk.defaults.v3`) so
 * Settings → Restore defaults can reload them offline.
 */
import { AssetRegistry, RiskConfig, TimeInForce } from './types';

export const DEFAULT_RISK_CONFIG: RiskConfig = {
  fixed_dollars_per_trade: 5,
  max_dollars_per_trade: 5,
  min_dollars_per_trade: 1,
  max_open_positions: 5,
  max_trades_per_day: 100,
  max_trades_per_asset_per_window: 1,
  daily_loss_stop_usd: 50,
  min_minutes_left: 2,
  min_minutes_elapsed: 2,
  max_entry_ask_usd: 0.9,
  time_in_force: 'immediate_or_cancel',
  manual_buy_time_in_force: 'immediate_or_cancel',
  chase_above_ask_usd: 0.02,
  protect_sell_enabled: false,
  protect_sell_gap_ratio: 1,
  protect_sell_grace_seconds: 45,
  smart_buy_enabled: true,
  smart_buy_min_edge_usd: 0.08,
  cash_out_enabled: false,
  cash_out_enter_pct: 60,
  cash_out_max_ask_usd: 0.82,
  cash_out_bid_usd: 0.88,
  cash_out_stop_usd: 0.05,
  cash_out_skip_thin_bid: false,
  cash_out_assets: ['Gold'],
  gold_fade_enabled: false,
  gold_fade_max_gap_usd: 3,
  gold_fade_max_ask_usd: 0.5,
  gold_fade_take_usd: 0.06,
  gold_fade_stop_usd: 0.05,
  gold_fade_flatten_minutes: 3,
  gold_fade_skip_thin_bid: false,
  twap_lock_enabled: false,
  twap_lock_assets: ['BTC', 'ETH'],
  twap_lock_max_ask_usd: 0.96,
  twap_lock_skip_thin_bid: false,
  last_minute_enabled: false,
  last_minute_side: 'yes',
  last_minute_max_ask_usd: 0.96,
  last_minute_watch_seconds: 150,
  last_minute_enter_seconds: 90,
  last_minute_stop_seconds: 10,
  last_minute_ladder_seconds: 2,
  last_minute_clip_count: 1,
  last_minute_max_clips: 5,
  last_minute_both_min_ask: 0.9,
  last_minute_both_gap: 0.1,
  last_minute_flip_sell_usd: 0,
  last_minute_skip_thin_bid: false,
  last_minute_assets: AssetRegistry.keys,
  step_buy_enabled: false,
  step_buy_start_minutes: 5,
  step_buy_cushion_pct: 50,
  step_buy_lot_count: 1,
  step_buy_add_wait_minutes: 1,
  step_buy_add_band_usd: 0.02,
  step_buy_max_lots: 3,
  step_buy_stop_usd: 0.03,
  step_buy_max_ask_usd: 0.8,
  step_buy_skip_thin_bid: false,
  step_buy_assets: AssetRegistry.keys,
};

export type RiskFieldGroup = 'size' | 'caps' | 'timing';

export const RISK_GROUPS: { id: RiskFieldGroup; label: string }[] = [
  { id: 'size', label: 'Size' },
  { id: 'caps', label: 'Caps' },
  { id: 'timing', label: 'Timing & protect' },
];

export const RISK_FIELD_META: {
  key: keyof RiskConfig;
  label: string;
  group: RiskFieldGroup;
  kind: 'money' | 'int' | 'tif' | 'chase' | 'toggle' | 'ratio' | 'seconds';
  step: number;
  min: number;
  max: number;
}[] = [
  { key: 'fixed_dollars_per_trade', label: '$ per trade', group: 'size', kind: 'money', step: 1, min: 1, max: 500 },
  { key: 'max_dollars_per_trade', label: 'Max $ / trade', group: 'size', kind: 'money', step: 1, min: 1, max: 500 },
  { key: 'min_dollars_per_trade', label: 'Min $ / trade', group: 'size', kind: 'money', step: 1, min: 1, max: 500 },
  { key: 'max_open_positions', label: 'Max open positions', group: 'caps', kind: 'int', step: 1, min: 1, max: 50 },
  { key: 'max_trades_per_day', label: 'Max trades / day', group: 'caps', kind: 'int', step: 1, min: 1, max: 50000 },
  {
    key: 'max_trades_per_asset_per_window',
    label: 'Max trades / asset / 15m window',
    group: 'caps',
    kind: 'int',
    step: 1,
    min: 1,
    max: 5,
  },
  { key: 'daily_loss_stop_usd', label: 'Daily loss stop ($)', group: 'caps', kind: 'money', step: 5, min: 1, max: 10000 },
  { key: 'min_minutes_left', label: 'Min minutes left (Buy only)', group: 'timing', kind: 'int', step: 1, min: 0, max: 14 },
  {
    key: 'min_minutes_elapsed',
    label: 'Min minutes elapsed (Buy only)',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 0,
    max: 10,
  },
  { key: 'max_entry_ask_usd', label: 'Max entry ask ($) (Buy limit)', group: 'timing', kind: 'chase', step: 0.01, min: 0.5, max: 0.99 },
  { key: 'time_in_force', label: 'Time in force', group: 'timing', kind: 'tif', step: 0, min: 0, max: 0 },
  { key: 'chase_above_ask_usd', label: 'Chase above ask ($)', group: 'timing', kind: 'chase', step: 0.01, min: 0, max: 0.05 },
  {
    key: 'smart_buy_enabled',
    label: 'Smart buy',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'smart_buy_min_edge_usd',
    label: 'Min extra chance ($)',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.04,
    max: 0.15,
  },
  {
    key: 'protect_sell_enabled',
    label: 'Protect money (early sell)',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'protect_sell_gap_ratio',
    label: 'Sell when gap ≥ cushion ×',
    group: 'timing',
    kind: 'ratio',
    step: 0.25,
    min: 0.5,
    max: 3,
  },
  {
    key: 'protect_sell_grace_seconds',
    label: 'Wait after fill before sell',
    group: 'timing',
    kind: 'seconds',
    step: 15,
    min: 0,
    max: 120,
  },
  {
    key: 'cash_out_enabled',
    label: 'Cash out',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'cash_out_enter_pct',
    label: 'Enter cushion (%)',
    group: 'timing',
    kind: 'int',
    step: 5,
    min: 40,
    max: 100,
  },
  {
    key: 'cash_out_max_ask_usd',
    label: 'Cash out max ask ($)',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.5,
    max: 0.99,
  },
  {
    key: 'cash_out_bid_usd',
    label: 'Cash out bid ($)',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.5,
    max: 0.99,
  },
  {
    key: 'cash_out_stop_usd',
    label: 'Cash out stop',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.03,
    max: 0.1,
  },
  {
    key: 'cash_out_skip_thin_bid',
    label: 'Skip thin bid',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'gold_fade_enabled',
    label: 'Gold fade',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'gold_fade_max_gap_usd',
    label: 'Max gap',
    group: 'timing',
    kind: 'money',
    step: 0.5,
    min: 1,
    max: 6,
  },
  {
    key: 'gold_fade_max_ask_usd',
    label: 'Max cheap ask',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.35,
    max: 0.55,
  },
  {
    key: 'gold_fade_take_usd',
    label: 'Take profit',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.05,
    max: 0.1,
  },
  {
    key: 'gold_fade_stop_usd',
    label: 'Gold fade stop',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.03,
    max: 0.1,
  },
  {
    key: 'gold_fade_flatten_minutes',
    label: 'Flatten with min left',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 2,
    max: 5,
  },
  {
    key: 'twap_lock_enabled',
    label: 'TWAP lock',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'twap_lock_max_ask_usd',
    label: 'Max ask',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.9,
    max: 0.97,
  },
  {
    key: 'last_minute_enabled',
    label: 'Last-minute',
    group: 'timing',
    kind: 'toggle',
    step: 0,
    min: 0,
    max: 1,
  },
  {
    key: 'last_minute_max_ask_usd',
    label: 'Entry ask',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.8,
    max: 0.99,
  },
  {
    key: 'last_minute_watch_seconds',
    label: 'Watch start (s left)',
    group: 'timing',
    kind: 'seconds',
    step: 5,
    min: 70,
    max: 180,
  },
  {
    key: 'last_minute_enter_seconds',
    label: 'First clip by (s left)',
    group: 'timing',
    kind: 'seconds',
    step: 5,
    min: 30,
    max: 150,
  },
  {
    key: 'last_minute_stop_seconds',
    label: 'Stop with (s left)',
    group: 'timing',
    kind: 'seconds',
    step: 1,
    min: 5,
    max: 20,
  },
  {
    key: 'last_minute_ladder_seconds',
    label: 'Ladder wait (s)',
    group: 'timing',
    kind: 'seconds',
    step: 1,
    min: 1,
    max: 5,
  },
  {
    key: 'last_minute_clip_count',
    label: 'Clip contracts',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 1,
    max: 5,
  },
  {
    key: 'last_minute_max_clips',
    label: 'Max clips',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 1,
    max: 20,
  },
  {
    key: 'last_minute_both_min_ask',
    label: 'Both min favorite',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.7,
    max: 0.95,
  },
  {
    key: 'last_minute_both_gap',
    label: 'Both min gap',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.05,
    max: 0.2,
  },
  {
    key: 'last_minute_flip_sell_usd',
    label: 'Sell if flip ≥',
    group: 'timing',
    kind: 'chase',
    step: 0.05,
    min: 0,
    max: 0.2,
  },
  { key: 'step_buy_enabled', label: 'Step buy', group: 'timing', kind: 'toggle', step: 1, min: 0, max: 1 },
  {
    key: 'step_buy_start_minutes',
    label: 'Start after',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 2,
    max: 10,
  },
  {
    key: 'step_buy_cushion_pct',
    label: 'Cushion %',
    group: 'timing',
    kind: 'int',
    step: 5,
    min: 25,
    max: 100,
  },
  {
    key: 'step_buy_lot_count',
    label: 'Lot contracts',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 1,
    max: 5,
  },
  {
    key: 'step_buy_add_wait_minutes',
    label: 'Add wait',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 1,
    max: 3,
  },
  {
    key: 'step_buy_add_band_usd',
    label: 'Add band',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0,
    max: 0.05,
  },
  {
    key: 'step_buy_max_lots',
    label: 'Max lots',
    group: 'timing',
    kind: 'int',
    step: 1,
    min: 1,
    max: 8,
  },
  {
    key: 'step_buy_stop_usd',
    label: 'Stop',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.01,
    max: 0.1,
  },
  {
    key: 'step_buy_max_ask_usd',
    label: 'Entry ask',
    group: 'timing',
    kind: 'chase',
    step: 0.01,
    min: 0.5,
    max: 0.9,
  },
];

export const TIME_IN_FORCE_OPTIONS: { value: TimeInForce; label: string }[] = [
  { value: 'immediate_or_cancel', label: 'IOC' },
  { value: 'good_till_canceled', label: 'GTC' },
  { value: 'fill_or_kill', label: 'FOK' },
];

export const SHARED_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'max_open_positions',
  'max_trades_per_day',
  'max_trades_per_asset_per_window',
  'daily_loss_stop_usd',
];

export const PATH_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'fixed_dollars_per_trade',
  'max_dollars_per_trade',
  'min_dollars_per_trade',
  'min_minutes_left',
  'min_minutes_elapsed',
  'max_entry_ask_usd',
  'time_in_force',
  'chase_above_ask_usd',
];

export const SMART_BUY_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'smart_buy_enabled',
  'smart_buy_min_edge_usd',
];

export const PROTECT_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'protect_sell_enabled',
  'protect_sell_gap_ratio',
  'protect_sell_grace_seconds',
];

export const CASH_OUT_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'cash_out_enabled',
  'cash_out_enter_pct',
  'cash_out_max_ask_usd',
  'cash_out_bid_usd',
  'cash_out_stop_usd',
  'cash_out_skip_thin_bid',
];

export const GOLD_FADE_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'gold_fade_enabled',
  'gold_fade_max_gap_usd',
  'gold_fade_max_ask_usd',
  'gold_fade_take_usd',
  'gold_fade_stop_usd',
  'gold_fade_flatten_minutes',
];

export const TWAP_LOCK_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'twap_lock_enabled',
  'twap_lock_max_ask_usd',
];

export const LAST_MINUTE_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'last_minute_enabled',
  'last_minute_max_ask_usd',
  'last_minute_watch_seconds',
  'last_minute_enter_seconds',
  'last_minute_stop_seconds',
  'last_minute_ladder_seconds',
  'last_minute_clip_count',
  'last_minute_max_clips',
  'last_minute_both_min_ask',
  'last_minute_both_gap',
  'last_minute_flip_sell_usd',
];

export const STEP_BUY_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  'step_buy_enabled',
  'step_buy_start_minutes',
  'step_buy_cushion_pct',
  'step_buy_lot_count',
  'step_buy_add_wait_minutes',
  'step_buy_add_band_usd',
  'step_buy_max_lots',
  'step_buy_stop_usd',
  'step_buy_max_ask_usd',
];

export const AUTO_ONLY_RISK_FIELD_KEYS: (keyof RiskConfig)[] = [
  ...SMART_BUY_RISK_FIELD_KEYS,
  ...PROTECT_RISK_FIELD_KEYS,
  ...CASH_OUT_RISK_FIELD_KEYS,
  ...GOLD_FADE_RISK_FIELD_KEYS,
  ...TWAP_LOCK_RISK_FIELD_KEYS,
  ...LAST_MINUTE_RISK_FIELD_KEYS,
  ...STEP_BUY_RISK_FIELD_KEYS,
];

export function cloneDefaultRisk(): RiskConfig {
  return { ...DEFAULT_RISK_CONFIG };
}
